name: Test
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-10.15,  windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: lint
        run: echo "Will lint..."
        # if: matrix.platform == 'ubuntu-latest'
        if: false

      - name: test rust backend
        run: cargo test --manifest-path=src-tauri/Cargo.toml
        if: matrix.platform == 'ubuntu-latest'

      - name: test rust frontend
        run: cargo test
        if: matrix.platform == 'ubuntu-latest'

      - name: Build app
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}